config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :favorites, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  get '/favorite_index_user', to: 'users#favorite_index'
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 140 }
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  validates :image, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  mount_uploader :image, ImageUploader
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  include SessionsHelper
  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end
  
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @picture.save
        #PictureMailer.picture_mail(@picture).deliver
        redirect_to pictures_path, notice: "投稿しました！"
      else
        render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"削除しました！"
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end


  private

  def picture_params
    params.require(:picture).permit(:title, :content, :email, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def check_login
      unless logged_in?
        flash[:notice] = "ログインしてください"
        redirect_to new_session_path
      end
  end

  def check_user
      unless current_user.id == @picture.user_id
        flash[:notice] = "編集権限がありません"
        redirect_to pictures_path
      end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
      flash[:notice] = 'ログアウトしました'
      redirect_to new_session_path
    end
  end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update, :show, :edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
      if @user.update(user_params)
        redirect_to user_path, notice: "編集しました！"
      else
        render :show
      end
  end

  def show
  end

  def favorite_index
    @favorite = current_user.favorite_pictures
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,
                                 :image, :image_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagramclone</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header class="header">InstagramClone</header>
  <div class="container">
  <nav class="menu">
    <ul class="row">
      <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <% if logged_in? %>
      <li class="col-md-6"><%= link_to "Profile", user_path(current_user.id) %></li>
      <li class="col-md-6"><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
      <% else %>
      <li class="col-md-6"><%= link_to "Sign up", new_user_path %>
        <br>
      </li>
      <li class="col-md-6"><%= link_to "Login", new_session_path %>
        <br>
      </li>
    </ul>
    <% end %>
  </nav>

  <%= yield %>
  
  </div>
</body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_new_or_edit ) do |form| %>
<% if @picture.errors.any? %>
<div id="error_explanation">
  <h2><%= @picture.errors.count %>件のエラーがあります。</h2>

  <ul>
    <% @picture.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="picture_title">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="picture_title">
  <%= form.label :content %>
  <%= form.text_field :content %>
</div>

<div class="field">
  <%= form.label :image %>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.file_field :image %>
  <%= form.hidden_field :image_cache %>
</div>

<%= form.submit %>
<% end %>
<%= link_to "投稿一覧画面にもどる", pictures_path %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @picture, local: true) do |form| %>
<%= form.hidden_field :title %>
<%= form.hidden_field :content %>
<%= form.hidden_field :image %>
<p>タイトル:<%= @picture.title %></p>
<p>本文:<%= @picture.content %></p>
<%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
<%= form.hidden_field :image_cache %>
<%= form.submit  "登録する" %>
<%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<%= form_with(model: @picture, local: true) do |form| %>
<% if @picture.errors.any? %>
<div id="error_explanation">
  <h2><%= @picture.errors.count %>件のエラーがあります。</h2>

  <ul>
    <% @picture.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>

</div>
<% end %>
<div class="picture_title">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="picture_content">
  <%= form.label :content %>
  <%= form.text_field :content %>
</div>

<div class="field">
  <%= form.label :image %>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.file_field :image %>
  <%= form.hidden_field :image_cache %>
</div>

<%= form.submit %>
<% end %>
<%= link_to "投稿一覧画面にもどる", pictures_path %>

app/views/pictures/index.html.erb
<h2>投稿一覧</h2>

<h3><%= link_to '新しく投稿する', new_picture_path %></h3>

<% @pictures.each do |picture| %>
<div class="contents">
  <ul>
    <li class="col-sm-12 col-md-offset-4 col-md-4">
      <h4>「<%= picture.title %>」</h4>
      <p><%= picture.content %></p>
      <p><%= image_tag(picture.image.url) %></p>
      <p>投稿者：<%= picture.user.name %></p>
      <br>
      <p><%= link_to '詳細を確認する', picture_path(picture.id) %></p>
      <% if logged_in? %>
        <% if picture.user_id == current_user.id %>
          <p><%= link_to "編集する", edit_picture_path(picture.id), data: { confirm: '本当に編集していいですか？' } %></p>
          <p><%= link_to '削除する', picture_path(picture.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></p>
        <% end %>
      <% end %>
    </li>
  </ul>
</div>
<% end %>

app/views/pictures/new.html.erb
<h2>投稿する</h2>
<%= render 'form' %>

app/views/pictures/show.html.erb
<h1>投稿詳細画面</h1>
<p>「<%= @picture.title %>」</p>
<p id="notice"><%= notice %></p>
<p><%= @picture.content %></p>
<p class="show_image"><strong>Image:</strong></p>
<p><%= image_tag @picture.image.url %></p>
<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<br>
<%= link_to "投稿一覧画面にもどる", pictures_path %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="user">
  <%= form_with(model: @user, local: true) do |f| %>
  <ul>
    <li><%= f.label :image %></li>
    <li class="image"><%= image_tag(@user.image.url) if @user.image && @user.image.url %></li>
  </ul>
  <ul>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </ul>
  <ul>
    <li><%= f.label :name %></li>
    <li><%= f.text_field :name %></li>
  </ul>
  <ul>
    <li><%= f.label :email %></li>
    <li><%= f.email_field :email %></li>
  </ul>
  <ul>
    <li><%= f.label :password %></li>
    <li><%= f.password_field :password %></li>
  </ul>
  <ul>
    <li><%= f.label :password_confirmation %></li>
    <li><%= f.password_field :password_confirmation %></li>
  </ul>

  <%= f.submit "Create my account" %>
  <% end %>

  <%= link_to "投稿一覧画面にもどる", pictures_path %>
</div>

app/views/users/favorite_index.html.erb
<h2>お気に入り一覧</h2>
<% @favorite.each do |favorite| %>
  <div class="contents">
        <h4>「<%= favorite.title %>」</h4>
      <p><%= favorite.content %></p>
      <p><%= image_tag(favorite.image.url) %></p>
      <p>投稿者：<%= favorite.user.name %></p>
      <p><%= favorite.updated_at %>に投稿</p>
    </div>
  <% end %>
  <%= link_to "Profileページにもどる", user_path(current_user.id) %></li>

app/views/users/new.html.erb
<h1>ようこそInstagramCloneへ！！</h1>
<h3>初めての方はSign upをお願いします。</h3>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="user">
<%= form_with(model: @user, local: true) do |f| %>
  <ul>
    <li><%= f.label :name %></li>
    <li><%= f.text_field :name %></li>
  </ul>
  <ul>
    <li><%= f.label :email %></li>
    <li><%= f.email_field :email %></li>
  </ul>
  <ul>
    <li><%= f.label :password %></li>
    <li><%= f.password_field :password %></li>
  </ul>
  <ul>
    <li><%= f.label :password_confirmation %></li>
    <li><%= f.password_field :password_confirmation %></li>
  </ul>
  <ul>
    <li><%= f.label :image %></li>
  <li><%= image_tag(@user.image.url) if @user.image && @user.image.url %></li>
  </ul>
  <li><%= f.file_field :image %></li>
  <li><%= f.hidden_field :image_cache %></li>

  <%= f.submit "Create my account" %>
  <% end %>

  <%= link_to "投稿一覧画面へ", pictures_path %>
</div>

app/views/users/show.html.erb
<% if logged_in? %>
<h1><%= @user.name %>のページ</h1>
<% else %>
<h1>ユーザー：<%= @user.name %>を登録しました。</h1>
<h2><%= link_to "ログイン", new_session_path %>してください</h2>
<% end %>
<br>
<p class="show_image"><strong>Image:</strong></p>
<p><%= image_tag @user.image.url %></p>
<br>
<p>メールアドレス: <%= @user.email %></p>
<br>
<%= link_to "ユーザー情報を編集する", edit_user_path(@user.id) %>
<br>
<%= link_to "お気に入り一覧", favorite_index_user_path(@user.id) %>
<br>
<%= link_to "投稿一覧画面へ", pictures_path(@user.id) %>